export const missoes = [
  {
    id: 1,
    titulo: "SENAICraft", 
    descricao: "'Gente, eu amo vocês! <3' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Thifany",
    status: 'disponivel',
    x: 100,
    y: 50,
    imagem: "assets/Images/Thifs.png",
  },
  {
    id: 2,
    titulo: "SENAICraft",
    descricao: "Quem mais chega atrasado no SENAI, além de mim?",
    respostaCorreta: "Vinicius",
    status: 'disponivel',
    x: 300,
    y: 140,
  },
  {
    id: 3,
    titulo: "SENAICraft",
    descricao: "'Toda tabela tem chave primária!!!' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Marcia",
    status: 'disponivel',
    x: 40,
    y: 350,
  },
  {
    id: 4,
    titulo: "SENAICraft",  
    descricao: "Quem é o aluno(a) ou professor(a) que digita na velocidade da luz?",
    respostaCorreta: "Dorival",
    status: 'disponivel',
    x: 90,
    y: 250,
  },
  {
    id: 5,
    titulo: "SENAICraft",  
    descricao: "'Hmmmmmmmmm... se alimentando... 😏😏' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Modesto",
    status: 'disponivel',
    x: 400,
    y: 200,
  }
  ,
  {
    id: 6,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) 'Frozen' da DS-15?",
    respostaCorreta: "Livia",
    status: 'disponivel',
    x: 200,
    y: 470,
  },
  {
    id: 7,
    titulo: "SENAICraft", 
    descricao: "'Esse verde não deu contraste com o branco!' qual aluno(a) ou professor(a) falou essa frase?",
    respostaCorreta: "Mariany",
    status: 'disponivel',
    x: 230,
    y: 300,
  }
  ,
  {
    id: 8,
    titulo: "SENAICraft", 
    descricao: "Quem é o maior hater de ratos da DS-15?",
    respostaCorreta: "Pedro",
    status: 'disponivel',
    x: 170,
    y: 160,
  },
  {
    id: 9,
    titulo: "SENAICraft",  
    descricao: "Quem está fazendo o DSGO na versão Hollow Knight?",
    respostaCorreta: "Ariane",
    status: 'disponivel',
    x: 120,
    y: 410,
  },
  {
    id: 10,
    titulo: "SENAICraft",
    descricao: "Qual aluno(a) ou professor(a) que chorou por causa do Cisco Packet Tracer?",
    respostaCorreta: "Duda",
    status: 'disponivel',
    x: 270,
    y: 30,
  },
  {
    id: 11,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) maior fã de Stardew Valley da DS-15?",
    respostaCorreta: "Joyce",
    status: 'disponivel',
    x: 380,
    y: 70,
  },
  {
    id: 12,
    titulo: "SENAICraft",   
    descricao: "'Comer, comer, comer pra poder crescer!' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Fernanda",
    status: 'disponivel',
    x: 500,
    y: 50,
  },
  {
    id: 13,
    titulo: "SENAICraft",  
    descricao: "'Vocês vão ter sprint com o Doná' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Lindomar",
    status: 'disponivel',
    x: 450,
    y: 130,
  },
  {
    id: 14,
    titulo: "SENAICraft",
    descricao: "'Olha só quem chegou! A Geovanna de Osasco!' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Israel",
    status: 'disponivel',
    x: 310,
    y: 260,
  },
  {
    id: 15,
    titulo: "SENAICraft", 
    descricao: "Quem é a pessoa mais engraçada da DS-15?",
    respostaCorreta: "Yngrid",
    status: 'disponivel',
    x: 290,
    y: 350,
  },
  {
    id: 16,
    titulo: "SENAICraft", 
    descricao: "Quem é a pessoa que vende as trufas mais deliciosas do mundo, da DS-15?",
    respostaCorreta: "Gabriela",
    status: 'disponivel',
    x: 310,
    y: 480,
  },
  {
    id: 17,
    titulo: "SENAICraft",  
    descricao: "Quem é o corintiano(a) mais apaixonado(a) da DS-15?",
    respostaCorreta: "Nicolas",
    status: 'disponivel',
    x: 600,
    y: 30,
  },
  {
    id: 18,
    titulo: "SENAICraft",  
    descricao: "Quem nasceu em Osasco? (Essa tá fácil demais!)",
    respostaCorreta: "Geovanna",
    status: 'disponivel',
    x: 400,
    y: 330,
  },
  {
    id: 19,
    titulo: "SENAICraft",   
    descricao: "Quem é o(a) melhor videomaker da DS-15?",
    respostaCorreta: "Evellyn",
    status: 'disponivel',
    x: 380,
    y: 430,
  },
  {
    id: 20,
    titulo: "SENAICraft",   
    descricao: "Quem é a pessoa mais tímida da DS-15?",
    respostaCorreta: "Lucas",
    status: 'disponivel',
    x: 540,
    y: 110,
  },
  {
    id: 21,
    titulo: "SENAICraft",   
    descricao: "Quem é a pessoa mais carismática da DS-15?",
    respostaCorreta: "Talita",
    status: 'disponivel',
    x: 460,
    y: 270,
  },
  {
    id: 22,
    titulo: "SENAICraft",   
    descricao: "Quem é o(a) mais dorminhoco(a) da DS-15? (Dica: tive que acordar ele(a) no fretado, uma vez...)",
    respostaCorreta: "Joao",
    status: 'disponivel',
    x: 160,
    y: 330,
  },
  {
    id: 23,
    titulo: "SENAICraft",
    descricao: "'Celton Melo!' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Vini",
    status: 'disponivel',
    x: 510,
    y: 220,
  },
  {
    id: 24,
    titulo: "SENAICraft",
    descricao: "'Hora do lanchinho...' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Vini",
    status: 'disponivel',
    x: 610,
    y: 180,
  },
  {
    id: 25,
    titulo: "SENAICraft",
    descricao: "'Tá chorando! Não pode chorar!' qual aluno(a) ou professor(a) fala essa frase?",
    respostaCorreta: "Modesto",
    status: 'disponivel',
    x: 570,
    y: 260,
  },
  {
    id: 26,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) que mais fala a palavra 'turminha'?",
    respostaCorreta: "Agatha",
    status: 'disponivel',
    x: 520,
    y: 330,
  },
  {
    id: 27,
    titulo: "SENAICraft",
    descricao: "'Ó ele(a) aí ó' qual aluno(a) ou professor(a) que fala essa frase?",
    respostaCorreta: "Lindomar",
    status: 'disponivel',
    x: 470,
    y: 390,
  },
  {
    id: 28,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) ou meio-oficial mais quieto(a) do DTA?",
    respostaCorreta: "Francis",
    status: 'disponivel',
    x: 440,
    y: 490,
  },
  {
    id: 29,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) ou meio-oficial mais descolado(a) do DTA?",
    respostaCorreta: "Cléber",
    status: 'disponivel',
    x: 560,
    y: 400,
  },
  {
    id: 30,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) ou meio-oficial mais divertido(a) do DTA?",
    respostaCorreta: "Vanessa",
    status: 'disponivel',
    x: 520,
    y: 460,
  },
  {
    id: 31,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) aluno(a) ou professor(a) que coloca música na sala da DS-15?",
    respostaCorreta: "Fernanda",
    status: 'disponivel',
    x: 670,
    y: 60,
  },
  {
    id: 32,
    titulo: "SENAICraft",
    descricao: "Quem tem o(a) pássaro mais fofo(a) da DS-15?",
    respostaCorreta: "Yngrid",
    status: 'disponivel',
    x: 520,
    y: 460,
  },
  {
    id: 33,
    titulo: "SENAICraft",
    descricao: "Quem leva comida na bolsa/mochila todo dia?",
    respostaCorreta: "Lucas",
    status: 'disponivel',
    x: 630,
    y: 490,
  },
  {
    id: 34,
    titulo: "SENAICraft",
    descricao: "'OLOKO!' qual aluno(a) ou professor(a) fala essa palavra?",
    respostaCorreta: "Joyce",
    status: 'disponivel',
    x: 670,
    y: 140,
  },
  {
    id: 35,
    titulo: "SENAICraft",
    descricao: "'Oii, pessoas!' qual é o Instrutor(a) ou meio-oficial que faz essa saudação?",
    respostaCorreta: "Vitoria",
    status: 'disponivel',
    x: 720,
    y: 200,
  },
  {
    id: 36,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) ou meio-oficial mais tímido do DTA? Dica: ex meio-oficial.",
    respostaCorreta: "Plinio",
    status: 'disponivel',
    x: 610,
    y: 320,
  },
  {
    id: 37,
    titulo: "SENAICraft",
    descricao: "Qual é o(a) instrutor(a) ou meio-oficial que ama as linguagens BackEnd?",
    respostaCorreta: "Fuzari",
    status: 'disponivel',
    x: 650,
    y: 400,
  },
  {
    id: 38,
    titulo: "SENAICraft",
    descricao: "'Ôôôôõ minininho(a)!' qual instrutor(a) ou meio-oficial que fala essa frase?",
    respostaCorreta: "Luca",
    status: 'disponivel',
    x: 670,
    y: 260,
  },
  {
    id: 39,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) ou meio-oficial que prefere comer vidro do que programar em qualquer linguagem FrontEnd?",
    respostaCorreta: "Willson",
    status: 'disponivel',
    x: 730,
    y: 340,
  },
  {
    id: 40,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) aluno(a) ou professor(a) mais estressado(a) da DS-15?",
    respostaCorreta: "Evellyn",
    status: 'disponivel',
    x: 770,
    y: 420,
  },
  {
    id: 41,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) ou meio-oficial que é amado(a) pela DS-18?",
    respostaCorreta: "Leonardo",
    status: 'disponivel',
    x: 710,
    y: 470,
  },
  {
    id: 42,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) ou meio-oficial que tem fundo de anime no computador? Dica: é apenas uma pessoa.",
    respostaCorreta: "Giovanna",
    status: 'disponivel',
    x: 805,
    y: 280,
  },
  {
    id: 43,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) aluno(a) ou professor(a) que tem a voz mais tranquila da DS-15?",
    respostaCorreta: "Gabriela",
    status: 'disponivel',
    x: 840,
    y: 340,
  },
  {
    id: 44,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) aluno(a) ou professor(a) mais fofo(a) da DS-15?",
    respostaCorreta: "Thifany",
    status: 'disponivel',
    x: 840,
    y: 440,
  },
  {
    id: 45,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) instrutor(a) ou meio-oficial mais velho do DTA? Dica: tempo trabalhado na empresa.",
    respostaCorreta: "Francis",
    status: 'disponivel',
    x: 900,
    y: 280,
  },
  {
    id: 46,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) aluno(a) que vai embora mais cedo da Bosch?",
    respostaCorreta: "Pedro",
    status: 'disponivel',
    x: 830,
    y: 170,
  },
  {
    id: 47,
    titulo: "SENAICraft",
    descricao: "Quem foi o(a) primeiro(a) aluno(a) a ganhar uma área na Bosch? Dica: não é o Lucas, Vinicius e Pedro.",
    respostaCorreta: "Duda",
    status: 'disponivel',
    x: 750,
    y: 120,
  },
  {
    id: 48,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) maior fã do bar do Tom Zé?",
    respostaCorreta: "Yngrid",
    status: 'disponivel',
    x: 820,
    y: 70,
  },
  {
    id: 49,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) mais viciado(a) em Valorant da DS-15?",
    respostaCorreta: "Nicolas",
    status: 'disponivel',
    x: 50,
    y: 130,
  },
  {
    id: 50,
    titulo: "SENAICraft",
    descricao: "Quem é o(a) melhor criador(a) de figurinhas da DS-15?",
    respostaCorreta: "Lucas",
    status: 'disponivel',
    x: 220,
    y: 230,
  },
];
